version: 0.0
os: linux
files:
  - source: /
    destination: /tmp
hooks:
  BeforeInstall:
    - location: scripts/app_stop.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/deploy.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/app_start.sh
      timeout: 300
      runas: root
